services:
  sing-box-client:
    image: ${CLIENT_SINGBOX_IMAGE:-ghcr.io/sagernet/sing-box:1.13.12}
    container_name: sing-box-client
    restart: always
    ports:
      - "${CLIENT_MIXED_PORT:-7890}:${CLIENT_MIXED_PORT:-7890}"
    volumes:
      - ./config:/etc/sing-box
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["run", "-c", "/etc/sing-box/config.json"]
